### PR TITLE
BugFix Dev

### LINKED ISSUE #1487: Outdated Dependency

### PR DESCRIPTION
**Pull request by Da-Colon**
Closes #1487

~see issue

### CODE REVIEW

**Review by adamgall — COMMENTED** [review]
I notice this removes the `graphql:build` step, which true, only needs to happen once on a dev's machine. 

It might make more sense for that to go into the `postinstall` script... What do you think?

https://docs.npmjs.com/cli/v10/using-npm/scripts#npm-install

**Comment by Da-Colon** [comment]
Actually don't think I meant to leave in that removal. but yeah seemed weird to build if it wasn't updated

**Comment by Da-Colon** [comment]
Yeah def makes sense. I've added the 'postinstall' script

| I'm just trying to figure out how to make that automatically happen without a (new) dev geting stuck or needing to think about it.

It runs directly after `npm install` is that what you mean? (I've just tested)

**Comment by adamgall** [comment]
> It runs directly after `npm install` is that what you mean? (I've just tested)

Yes! This is what I was expecting. This satisfies what I was after, as far as I can tell.

**Review by adamgall — APPROVED** [review]

**Pull request merged**
