### PR TITLE
`Reskin` - root reskin review bug fixes

### PR DESCRIPTION
**Pull request by mudrila**
This PR addresses following comments:
- https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2093632142 (All 5 of mentioned)
- https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2093642261
- https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2093654797
- https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2093656129
- https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2093666493 @nicolaus-sherrill pls check that alignment looks right
- https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2093670292 @nicolaus-sherrill @xraystyle1980 pls check focused state - should it have same box shadowing or it also should be red
- https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2093672219 - removed tooltip but keeping this as `Link` so that user could right-click link and copy URL
- https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2093680208 - @nicolaus-sherrill did I get it right that size should be 20x20 px here? Or you've meant removing border? I made it sized bigger though it was exactly like in Figma
- https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2093689614
- https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2096378028
- https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2096389291
- https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2096390587
- https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2096398548

### CODE REVIEW

**Review by adamgall — CHANGES_REQUESTED** [review]
> https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2093632142 (All 5 of mentioned)
>> 1. the user would click on the menu before it opens, rather than the current open-on-hover

still "open on hover" effect going on

>> 2. There shouldn't be a gap in between these menu sections on the bottom sidebar menu. That should be a full-width divider stroke, same as the other menus with sections.

need to add dividers between all of the menu icons

>> 3. Make sure that all of the menus have consistent transparency & blur applied to them.

It doesn't look like there is any blur applied on the various menus, just transparency.

Screenshot 2024-05-08 at 4 37 00 PM

The sidebar menus don't have _any_ transparency (or blur) on them.

Screenshot 2024-05-08 at 4 36 21 PM

---

> https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2093642261

This icon is now showing up super tiny for me

Screenshot 2024-05-08 at 4 35 21 PM

---

> https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2093656129

Not sure if this is part of this issue, but getting some cutoff on this etherscan link. From the following link: https://deploy-preview-1678.app.dev.fractalframework.xyz/proposals/0xb8a3c88c9fad69729211bb736c3d19df69b620dd87e21059b3b46380fe05d121?dao=eth:0xD26c85D435F02DaB8B220cd4D2d398f6f646e235

Screenshot 2024-05-08 at 4 39 40 PM

---

> https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2093672219

Looking at the same link from previous comment (https://deploy-preview-1678.app.dev.fractalframework.xyz/proposals/0xb8a3c88c9fad69729211bb736c3d19df69b620dd87e21059b3b46380fe05d121?dao=eth:0xD26c85D435F02DaB8B220cd4D2d398f6f646e235)

The button pill thing here still has a "View in Etherscan" hover text and is a link to etherscan, doesn't copy the address.

I suggest we keep this behavior consistent throughout the app, especially if we're going to be styling these things the same. @nicolaus-sherrill please give your thoughts.

---

> https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2093689614

Getting some of the final character cut off

Screenshot 2024-05-08 at 4 45 16 PM

---

> https://github.com/decentdao/fractal-interface/pull/1578#issuecomment-2096398548

Still seeing various alignment and non-line-breaking issues

Screenshot 2024-05-08 at 4 48 55 PM
Screenshot 2024-05-08 at 4 49 51 PM
Screenshot 2024-05-08 at 4 50 04 PM

**Comment by nicolaus-sherrill** [comment]
@adamgall in regards to the comment about the ghost text buttons & copying to clipboard vs opening in Etherscan, I agree with you — functionality should be the same. Regardless, a tooltip communicating an action to a user should be accurate, so thanks for removing that tooltip for the "copy address" button at the top of the DAO Home page.


One solution that comes to mind is a different style on hover for actual text links vs buttons — we could throw in an underline on hover and/or drop an angled-northeast-arrow icon at the right to communicate that the user will be taken to a new experience. I'll open a design issue about this for us. @xraystyle1980 @xanaramoss FYI

**Comment by nicolaus-sherrill** [comment]
screenshot

Align the languages submenu with the bottom of the Languages menu list item. (Language list ascends up from the bottom)


(PS I would normally recommend the alignment be to the top of the item and descend downward, but since this is at the bottom of the screen, we ought to push content up instead of down)
<details><summary>Browser metadata</summary>





```
Path:      /home?dao=eth:0xD26c85D435F02DaB8B220cd4D2d398f6f646e235
Browser:   Firefox 125.0 on Mac OS 10.15
Viewport:  1342 x 910 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1678.app.dev.fractalframework.xyz%2Fhome%3Fdao%3Deth%3A0xD26c85D435F02DaB8B220cd4D2d398f6f646e235&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=125.0&resolution=1342x910&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1678.app.dev.fractalframework.xyz/home?dao=eth:0xD26c85D435F02DaB8B220cd4D2d398f6f646e235) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663bde5b0f02490008dcb831&commentID=663beb86d9697c05b4ec3433&resolution=resolved)

**Comment by nicolaus-sherrill** [comment]
screenshot

Trash can should follow same ghost button style as the Favorites and Settings.
<details><summary>Browser metadata</summary>





```
Path:      /create
Browser:   Firefox 125.0 on Mac OS 10.15
Viewport:  1454 x 910 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1678.app.dev.fractalframework.xyz%2Fcreate&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=125.0&resolution=1454x910&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1678.app.dev.fractalframework.xyz/create) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663bde5b0f02490008dcb831&commentID=663bec30ea36e508fc46fff6&resolution=resolved)

**Comment by nicolaus-sherrill** [comment]
@adamgall disregard my comments about sidebar click on open. I was gaslighting myself on the intended functionality.

**Review by nicolaus-sherrill — CHANGES_REQUESTED** [review]
Feedback left already above. Nice work on the buggier pieces here.

**Comment by adamgall** [comment]
Merging this right now, and will create issues for all of the comments being left on requested changes for the work in this PR. Future PRs should be smaller scoped to just one piece of feedback or group of related feedback.

**Pull request merged**
